import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import ThemeSwitcher from "./components/ThemeSwitcher";
import { LIFFContextProvider } from "./context/LiffProvider";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LIFF DEMO APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LIFFContextProvider>
          <Providers>
            <header className="py-6">
              <nav className="container flex items-center justify-between">
                <ul>
                  <li>
                    <Link href="/">READY TO WORK</Link>
                  </li>
                </ul>
                <ThemeSwitcher />
              </nav>
            </header>
            <main>{children}</main>
            <footer></footer>
          </Providers>
        </LIFFContextProvider>
      </body>
    </html>
  );
}
